"""

Revision ID: 49c85af08b60
Revises: 0746d3057232
Create Date: 2025-11-13 19:47:35.923333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49c85af08b60'
down_revision: Union[str, Sequence[str], None] = '0746d3057232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('contacts_email_key'), 'contacts', type_='unique')
    op.drop_constraint(op.f('contacts_phone_number_key'), 'contacts', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('contacts_phone_number_key'), 'contacts', ['phone_number'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('contacts_email_key'), 'contacts', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
